---
- hosts: all
  become: true
  vars:
    homefolder: /home/ubuntu
  tasks:
    # security
    - name: security patches for Ubuntu
      apt:
        upgrade: yes
        update_cache: yes
      when: ansible_os_family == "Debian"
    - name: security patches for AWS linux
      yum:
        upgrade: yes
        update_cache: yes
      when: ansible_distribution == "Amazon"

    # docker
    - name: prune docker
      command: docker system prune -f
    - name: pull docker images
      command: docker compose -f {{homefolder}}/docker-compose.yml pull
    - name: pull docker images
      command: docker compose -f {{homefolder}}/docker-compose.yml up -d
    - name: get docker status
      command: docker ps
