---
- hosts: all
  become: true
  vars:
    homefolder: /home/ubuntu
  tasks:
    - name: security patches
      apt:
        upgrade: yes
        update_cache: yes
    - name: pull docker images
      command: docker compose -f {{homefolder}}/docker-compose.yml pull
    - name: pull docker images
      command: docker compose -f {{homefolder}}/docker-compose.yml up -d
    - name: get docker status
      command: docker ps
