---
- hosts: all
  become: true
  tasks:
 
    - name: refresh gitlab token
      environment:
        CI_REGISTRY: registry.gitlab.com
        CI_REGISTRY_TOKEN_NAME: ec2-image-pull
      shell: |
        ST_KEY=$(curl -s http://169.254.169.254/latest/meta-data/tags/instance/Gitlab)
        export CI_TOKEN="glpat"-$(aws secretsmanager get-secret-value --secret-id secret-aipo-mlops-gitlab-token | jq -r --arg ST_KEY "$ST_KEY" '.SecretString | fromjson | .[$ST_KEY]')
        docker logout "$CI_REGISTRY"
        docker login -u "$CI_REGISTRY_TOKEN_NAME" -p "$CI_TOKEN" "$CI_REGISTRY"
        unset CI_TOKEN
      register: output
 
    - name: print std output
      debug:
        var: output.stdout_lines
 
    - name: Verify login succeeded
      fail:
        msg: "Login failed. 'Login Succeeded' not found in the output."
      when: "'Login Succeeded' not in output.stdout"
